class PenteraTasks < Thor
  include Rails.application.config.dradis.thor_helper_module

  namespace 'dradis:plugins:pentera'

  desc      'upload FILE', 'upload Pentera results in JSON format'
  long_desc 'This plugin expects a JSON file generated by Pentera'
  method_option :state,
    type: :string,
    desc: 'The state your issues will be created with. If not provided, the scope will be draft'
  def upload(file_path)
    require 'config/environment'

    unless File.exists?(file_path)
      $stderr.puts "** the file [#{file_path}] does not exist"
      exit(-1)
    end

    detect_and_set_project_scope

    importer = Dradis::Plugins::Pentera::Importer.new(task_options)
    importer.import(file: file_path)
  end
end
